<a href="https://colab.research.google.com/github/taheer619/Pytorch-Tutorial/blob/main/intro_to_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch


In [1]:
import numpy as np

In [2]:
my_list=[13,4,5,6,7,]
print(my_list)

[13, 4, 5, 6, 7]


LIST

In [3]:
my_list=[[1,2,3],[3,5,6],[34,0,9]]
my_list


[[1, 2, 3], [3, 5, 6], [34, 0, 9]]

In [6]:
np1=np.random.rand(4)
np1

array([0.08505442, 0.66869983, 0.51176388, 0.59942321])

In [5]:
np1.dtype

dtype('float64')

In [9]:
tensor_2d1=torch.randn(4)

In [11]:
tensor_2d1.dtype

torch.float32

In [12]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
my_tensor=torch.tensor(np1)

In [14]:
my_tensor

tensor([0.0851, 0.6687, 0.5118, 0.5994], dtype=torch.float64)