<a href="https://colab.research.google.com/github/taheer619/Pytorch-Tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [7]:
my_torch=torch.arange(10)

In [8]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_torch.reshape(2,5)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch=torch.arange(22)
my_torch.reshape(-1,2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21]])

In [17]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch1=my_torch.view(2,5)

In [20]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#difference between shape and view
